quarkus.config.locations=file:///D:/Estudio/Universidad/DAD/SEM02/ms-base/central.config/common.properties,file:///D:/Estudio/Universidad/DAD/SEM02/ms-base/central.config/ms-curso.properties
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.swagger-ui.always-include=true