quarkus.application.name=ms-alumnos
quarkus.http.port=8081

#base de dato propia
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/bd_alumnos
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.swagger-ui.always-include=true

mensaje.servicio = Microservicio de alumnos ok?
